const SENDER_NAMES = [
  "Mohamed A*** B**** K****",
  "Ahmed M*** R**** N****",
  "Youssef S*** N**** Z****",
  "Mahmoud T*** Z**** W****",
  "Kareem G*** W**** Y****",
  "Tarek B*** Y**** R****",
  "Mostafa K*** R**** A****",
  "Omar R*** A**** M****",
  "Ali N*** M**** S****",
  "Hassan Z*** S**** T****",
  "Hussein W*** T**** G****",
  "Ibrahim Y*** G**** B****",
  "Eslam R*** B**** K****",
  "Khaled A*** K**** R****",
  "Amr M*** R**** N****",
  "Mohamed S*** N**** Z****",
  "Ahmed T*** Z**** W****",
  "Youssef G*** W**** Y****",
  "Mahmoud B*** Y**** R****",
  "Kareem K*** R**** A****",
  "Tarek R*** A**** M****",
  "Mostafa N*** M**** S****",
  "Omar Z*** S**** T****",
  "Ali W*** T**** G****",
  "Hassan Y*** G**** B****",
  "Hussein R*** B**** K****",
  "Ibrahim A*** K**** R****",
  "Eslam M*** R**** N****",
  "Khaled S*** N**** Z****",
  "Amr T*** Z**** W****",
  "Mohamed G*** W**** Y****",
  "Ahmed B*** Y**** R****",
  "Youssef K*** R**** A****",
  "Mahmoud R*** A**** M****",
  "Kareem N*** M**** S****",
  "Tarek Z*** S**** T****",
  "Mostafa W*** T**** G****",
  "Omar Y*** G**** B****",
  "Ali R*** B**** K****",
  "Hassan A*** K**** R****",
  "Hussein M*** R**** N****",
  "Ibrahim S*** N**** Z****",
  "Eslam T*** Z**** W****",
  "Khaled G*** W**** Y****",
  "Amr B*** Y**** R****",
  "Mohamed K*** R**** A****",
  "Ahmed R*** A**** M****",
  "Youssef N*** M**** S****",
  "Mahmoud Z*** S**** T****",
  "Kareem W*** T**** G****",
  "Tarek Y*** G**** B****",
  "Mostafa R*** B**** K****",
  "Omar A*** K**** R****",
  "Ali M*** R**** N****",
  "Hassan S*** N**** Z****",
  "Hussein T*** Z**** W****",
  "Ibrahim G*** W**** Y****",
  "Eslam B*** Y**** R****",
  "Khaled K*** R**** A****",
  "Amr R*** A**** M****",
  "Mohamed N*** M**** S****",
  "Ahmed Z*** S**** T****",
  "Youssef W*** T**** G****",
  "Mahmoud Y*** G**** B****",
  "Kareem R*** B**** K****",
  "Tarek A*** K**** R****",
  "Mostafa M*** R**** N****",
  "Omar S*** N**** Z****",
  "Ali T*** Z**** W****",
  "Hassan G*** W**** Y****",
  "Hussein B*** Y**** R****",
  "Ibrahim K*** R**** A****",
  "Eslam R*** A**** M****",
  "Khaled N*** M**** S****",
  "Amr Z*** S**** T****",
  "Mohamed W*** T**** G****",
  "Ahmed Y*** G**** B****",
  "Youssef R*** B**** K****",
  "Mahmoud A*** K**** R****",
  "Kareem M*** R**** N****",
  "Tarek S*** N**** Z****",
  "Mostafa T*** Z**** W****",
  "Omar G*** W**** Y****",
  "Ali B*** Y**** R****",
  "Hassan K*** R**** A****",
  "Hussein R*** A**** M****",
  "Ibrahim N*** M**** S****",
  "Eslam Z*** S**** T****",
  "Khaled W*** T**** G****",
  "Amr Y*** G**** B****",
  "Mohamed R*** B**** K****",
  "Ahmed A*** K**** R****",
  "Youssef M*** R**** N****",
  "Mahmoud S*** N**** Z****",
  "Kareem T*** Z**** W****",
  "Tarek G*** W**** Y****",
  "Mostafa B*** Y**** R****",
  "Omar K*** R**** A****",
  "Ali R*** A**** M****",
  "Hassan N*** M**** S****",
  "Hussein Z*** S**** T****",
  "Ibrahim W*** T**** G****",
  "Eslam Y*** G**** B****",
  "Khaled R*** B**** K****",
  "Amr A*** K**** R****",
  "Mohamed M*** R**** N****",
  "Ahmed S*** N**** Z****",
  "Youssef T*** Z**** W****",
  "Mahmoud G*** W**** Y****",
  "Kareem B*** Y**** R****",
  "Tarek K*** R**** A****",
  "Mostafa R*** A**** M****",
  "Omar N*** M**** S****",
  "Ali Z*** S**** T****",
  "Hassan W*** T**** G****",
  "Hussein Y*** G**** B****",
  "Ibrahim R*** B**** K****",
  "Eslam A*** K**** R****",
  "Khaled M*** R**** N****",
  "Amr S*** N**** Z****",
  "Mohamed T*** Z**** W****",
  "Ahmed G*** W**** Y****",
  "Youssef B*** Y**** R****",
  "Mahmoud K*** R**** A****",
  "Kareem R*** A**** M****",
  "Tarek N*** M**** S****",
  "Mostafa Z*** S**** T****",
  "Omar W*** T**** G****",
  "Ali Y*** G**** B****",
  "Hassan R*** B**** K****",
  "Hussein A*** K**** R****",
  "Ibrahim M*** R**** N****",
  "Eslam S*** N**** Z****",
  "Khaled T*** Z**** W****",
  "Amr G*** W**** Y****",
  "Mohamed B*** Y**** R****",
  "Ahmed K*** R**** A****",
  "Youssef R*** A**** M****",
  "Mahmoud N*** M**** S****",
  "Kareem Z*** S**** T****",
  "Tarek W*** T**** G****",
  "Mostafa Y*** G**** B****",
  "Omar R*** B**** K****",
  "Ali A*** K**** R****",
  "Hassan M*** R**** N****",
  "Hussein S*** N**** Z****",
  "Ibrahim T*** Z**** W****",
  "Eslam G*** W**** Y****",
  "Khaled B*** Y**** R****",
  "Amr K*** R**** A****",
];

/**
 * Returns the sender name for a phone number.
 * The mapping is deterministic: the same phone number always gets the same name.
 */
export function getSenderNameForPhone(phone: string): string {
  const digits = (phone || "").replace(/\D/g, "");
  const key = digits || "unknown";

  let hash = 5381;
  for (let i = 0; i < key.length; i++) {
    hash = ((hash << 5) + hash + key.charCodeAt(i)) >>> 0;
  }

  return SENDER_NAMES[hash % SENDER_NAMES.length] ?? SENDER_NAMES[0] ?? "";
}
